from .app import *
from .base import Always, Condition, Filter, FilterOrBool, Never
from .cli import *, __all__ as cli_all
from .utils import is_true, to_filter

from apptk.filters.app import display_has_focus, has_toolbar, scrollable
from apptk.filters.buffer import (
    at_end_of_buffer,
    buffer_is_code,
    buffer_is_empty,
    buffer_is_markdown,
    buffer_name_is,
    char_after_cursor,
    cursor_at_end_of_line,
    cursor_at_start_of_line,
    cursor_in_leading_ws,
    cursor_on_first_line,
    cursor_on_last_line,
    has_matching_bracket,
    has_suggestion,
    is_returnable,
)
from apptk.filters.environment import (
    command_exists,
    have_modules,
    in_mplex,
    in_screen,
    in_tmux,
)
from apptk.filters.modes import (
    exitable_mode,
    helix_insert_mode,
    helix_mode,
    helix_navigation_mode,
    helix_replace_mode,
    insert_mode,
    micro_insert_mode,
    micro_mode,
    micro_recording_macro,
    micro_replace_mode,
    navigation_mode,
    replace_mode,
)


__all__ = [
    "has_arg",
    "has_completions",
    "completion_is_selected",
    "has_focus",
    "buffer_has_focus",
    "has_selection",
    "has_validation_error",
    "is_done",
    "is_read_only",
    "is_multiline",
    "renderer_height_is_known",
    "in_editing_mode",
    "in_paste_mode",
    "vi_mode",
    "vi_navigation_mode",
    "vi_insert_mode",
    "vi_insert_multiple_mode",
    "vi_replace_mode",
    "vi_selection_mode",
    "vi_waiting_for_text_object_mode",
    "vi_digraph_mode",
    "vi_recording_macro",
    "emacs_mode",
    "emacs_insert_mode",
    "emacs_selection_mode",
    "shift_selection_mode",
    "is_searching",
    "control_is_searchable",
    "vi_search_direction_reversed",
    "Filter",
    "Never",
    "Always",
    "Condition",
    "FilterOrBool",
    "is_true",
    "to_filter",
    "at_end_of_buffer",
    "buffer_is_code",
    "buffer_is_empty",
    "buffer_is_markdown",
    "buffer_name_is",
    "char_after_cursor",
    "command_exists",
    "cursor_at_end_of_line",
    "cursor_at_start_of_line",
    "cursor_in_leading_ws",
    "cursor_on_first_line",
    "cursor_on_last_line",
    "display_has_focus",
    "exitable_mode",
    "has_matching_bracket",
    "has_suggestion",
    "has_toolbar",
    "have_modules",
    "helix_insert_mode",
    "helix_mode",
    "helix_navigation_mode",
    "helix_replace_mode",
    "in_mplex",
    "in_screen",
    "in_tmux",
    "insert_mode",
    "is_returnable",
    "micro_insert_mode",
    "micro_mode",
    "micro_recording_macro",
    "micro_replace_mode",
    "navigation_mode",
    "replace_mode",
    "scrollable",
]
