from abc import abstractmethod
from collections.abc import Callable, Iterable
from typing import Union

class Filter:
    _and_cache: dict[Filter, Filter]
    _or_cache: dict[Filter, Filter]
    _invert_result: Filter | None
    def __init__(self) -> None: ...
    @abstractmethod
    def __call__(self) -> bool: ...
    def __and__(self, other: Filter) -> Filter: ...
    def __or__(self, other: Filter) -> Filter: ...
    def __invert__(self) -> Filter: ...
    def __bool__(self) -> None: ...

FilterOrBool = Union[Filter, bool]

__all__ = [
    "Always",
    "Condition",
    "Filter",
    "FilterOrBool",
    "Never",
]

class _AndList(Filter):
    filters: list[Filter]
    def __init__(self, filters: list[Filter]) -> None: ...
    @classmethod
    def create(cls, filters: Iterable[Filter]) -> Filter: ...
    def __call__(self) -> bool: ...
    def __repr__(self) -> str: ...

class _OrList(Filter):
    filters: list[Filter]
    def __init__(self, filters: list[Filter]) -> None: ...
    @classmethod
    def create(cls, filters: Iterable[Filter]) -> Filter: ...
    def __call__(self) -> bool: ...
    def __repr__(self) -> str: ...

class _Invert(Filter):
    filter: Filter
    def __init__(self, filter: Filter) -> None: ...
    def __call__(self) -> bool: ...
    def __repr__(self) -> str: ...

class Always(Filter):
    def __call__(self) -> bool: ...
    def __and__(self, other: Filter) -> Filter: ...
    def __or__(self, other: Filter) -> Filter: ...
    def __invert__(self) -> Never: ...

class Never(Filter):
    def __call__(self) -> bool: ...
    def __and__(self, other: Filter) -> Filter: ...
    def __or__(self, other: Filter) -> Filter: ...
    def __invert__(self) -> Always: ...

class Condition(Filter):
    func: Callable[[], bool]
    def __init__(self, func: Callable[[], bool]) -> None: ...
    def __call__(self) -> bool: ...
    def __repr__(self) -> str: ...
