"""Miscellaneous control fields."""

from __future__ import annotations

from functools import cached_property
from typing import TYPE_CHECKING

from euporie.apptk.utils import get_cwidth
from prompt_toolkit.layout.controls import UIContent as PtkUIContent
from prompt_toolkit.layout.controls import UIControl

from euporie.apptk.data_structures import Point
from euporie.apptk.formatted_text.utils import _ZERO_WIDTH_FRAGMENTS

if TYPE_CHECKING:
    from euporie.apptk.formatted_text import StyleAndTextTuples


class UIContent(PtkUIContent):
    """Content generated by a user control.

    Adds ability to search for the position of graphics.
    """

    @cached_property
    def graphic_positions(self) -> dict[str, Point]:
        """Scan content lines for graphic markers and return their positions.

        Returns:
            Dictionary mapping graphic keys to their (x, y) positions in content coordinates.
        """
        positions: dict[str, Point] = {}
        get_line = self.get_line
        for y in range(self.line_count):
            line = get_line(y)
            x = 0
            for style, text, *_ in line:
                for part in style.split():
                    if part.startswith("[Graphic_"):
                        key = part[9:-1]  # Extract key from [Graphic_xxx]
                        positions[key] = Point(x, y)
                    if part in _ZERO_WIDTH_FRAGMENTS:
                        break
                else:
                    x += get_cwidth(text)
        return positions


class DummyControl(UIControl):
    """A dummy control object that doesn't paint any content."""

    def create_content(self, width: int, height: int) -> UIContent:
        """Return one blank line only."""

        def get_line(i: int) -> StyleAndTextTuples:
            return []

        return UIContent(get_line=get_line, line_count=1)


class FocusableDummyControl(DummyControl):
    """A dummy control object that doesn't paint any content."""

    def is_focusable(self) -> bool:
        """Make this control focusable."""
        return True
