from .key_processor import KeyPress

__all__ = [
    "EmacsState",
]

class EmacsState:
    macro: list[KeyPress] | None
    current_recording: list[KeyPress] | None
    def __init__(self) -> None: ...
    def reset(self) -> None: ...
    @property
    def is_recording(self) -> bool: ...
    def start_macro(self) -> None: ...
    def end_macro(self) -> None: ...
