import logging
from collections.abc import Callable
from typing import TypeVar, Union

from apptk.commands import add_cmd, get_cmd
from apptk.key_binding.key_bindings import Binding
from apptk.key_binding.key_processor import KeyPressEvent

_Handler = Callable[[KeyPressEvent], None]
_HandlerOrBinding = Union[_Handler, Binding]
_T = TypeVar("_T", bound=_HandlerOrBinding)
E = KeyPressEvent
_readline_commands: dict[str, Binding] = {}
log = logging.getLogger(__name__)
register = add_cmd
get_by_name = get_cmd

__all__ = [
    "get_by_name",
    "toggle_comments",
]

def register(name: str) -> Callable[[_T], _T]: ...
def get_by_name(name: str) -> Binding: ...
def beginning_of_buffer(event: E) -> None: ...
def end_of_buffer(event: E) -> None: ...
def beginning_of_line(event: E) -> None: ...
def end_of_line(event: E) -> None: ...
def forward_char(event: E) -> None: ...
def backward_char(event: E) -> None: ...
def forward_word(event: E) -> None: ...
def backward_word(event: E) -> None: ...
def clear_screen(event: E) -> None: ...
def redraw_current_line(event: E) -> None: ...
def accept_line(event: E) -> None: ...
def previous_history(event: E) -> None: ...
def next_history(event: E) -> None: ...
def beginning_of_history(event: E) -> None: ...
def end_of_history(event: E) -> None: ...
def reverse_search_history(event: E) -> None: ...
def end_of_file(event: E) -> None: ...
def delete_char(event: E) -> None: ...
def backward_delete_char(event: E) -> None: ...
def self_insert(event: E) -> None: ...
def transpose_chars(event: E) -> None: ...
def uppercase_word(event: E) -> None: ...
def downcase_word(event: E) -> None: ...
def capitalize_word(event: E) -> None: ...
def quoted_insert(event: E) -> None: ...
def kill_line(event: E) -> None: ...
def kill_word(event: E) -> None: ...
def unix_word_rubout(event: E, WORD: bool = True) -> None: ...
def backward_kill_word(event: E) -> None: ...
def delete_horizontal_space(event: E) -> None: ...
def unix_line_discard(event: E) -> None: ...
def yank(event: E) -> None: ...
def yank_nth_arg(event: E) -> None: ...
def yank_last_arg(event: E) -> None: ...
def yank_pop(event: E) -> None: ...
def complete(event: E) -> None: ...
def menu_complete(event: E) -> None: ...
def menu_complete_backward(event: E) -> None: ...
def start_kbd_macro(event: E) -> None: ...
def end_kbd_macro(event: E) -> None: ...
def call_last_kbd_macro(event: E) -> None: ...
def print_last_kbd_macro(event: E) -> None: ...
def undo(event: E) -> None: ...
def insert_comment(event: KeyPressEvent) -> None: ...
def vi_editing_mode(event: E) -> None: ...
def emacs_editing_mode(event: E) -> None: ...
def prefix_meta(event: E) -> None: ...
def operate_and_get_next(event: E) -> None: ...
def edit_and_execute(event: E) -> None: ...
def toggle_comments(event: KeyPressEvent) -> None: ...
