from apptk.key_binding.key_processor import KeyPressEvent

E = KeyPressEvent

__all__ = [
    "scroll_backward",
    "scroll_forward",
    "scroll_half_page_down",
    "scroll_half_page_up",
    "scroll_one_line_down",
    "scroll_one_line_up",
]

def scroll_forward(event: E, half: bool = False) -> None: ...
def scroll_backward(event: E, half: bool = False) -> None: ...
def scroll_half_page_down(event: E) -> None: ...
def scroll_half_page_up(event: E) -> None: ...
def scroll_one_line_down(event: E) -> None: ...
def scroll_one_line_up(event: E) -> None: ...
def scroll_page_down(event: E) -> None: ...
def scroll_page_up(event: E) -> None: ...
