from apptk.key_binding.key_processor import KeyPressEvent

E = KeyPressEvent

__all__ = [
    "abort_search",
    "accept_search",
    "accept_search_and_accept_input",
    "forward_incremental_search",
    "reverse_incremental_search",
    "start_forward_incremental_search",
    "start_reverse_incremental_search",
]

def abort_search(event: E) -> None: ...
def accept_search(event: E) -> None: ...
def start_reverse_incremental_search(event: E) -> None: ...
def start_forward_incremental_search(event: E) -> None: ...
def reverse_incremental_search(event: E) -> None: ...
def forward_incremental_search(event: E) -> None: ...
def accept_search_and_accept_input(event: E) -> None: ...
