"""Miscellaneous control fields."""

from __future__ import annotations

import logging
from functools import cached_property
from typing import TYPE_CHECKING

from apptk.data_structures import Point
from apptk.formatted_text.utils import _ZERO_WIDTH_FRAGMENTS
from apptk.lexers import DynamicLexer
from apptk.lexers.pygments import PygmentsLexer
from apptk.utils import get_cwidth
from prompt_toolkit.layout.controls import (
    BufferControl as PtkBufferControl,
)
from prompt_toolkit.layout.controls import (
    GetLinePrefixCallable,
    UIControl,
)
from prompt_toolkit.layout.controls import UIContent as PtkUIContent

if TYPE_CHECKING:
    from apptk.formatted_text import StyleAndTextTuples

__all__ = [
    "BufferControl",
    "DummyControl",
    "FocusableDummyControl",
    "GetLinePrefixCallable",
    "UIContent",
]

log = logging.getLogger(__name__)


class BufferControl(PtkBufferControl):
    """Extended BufferControl that exposes the buffer's language."""

    @property
    def language(self) -> str | None:
        """Return the language of the buffer based on the current lexer.

        Returns:
            The language name in lowercase, or an empty string if unknown.
        """
        lexer = self.lexer
        if isinstance(lexer, DynamicLexer):
            lexer = lexer.get_lexer()
        if isinstance(lexer, PygmentsLexer):
            return lexer.pygments_lexer_cls.name.lower()
        return None


class UIContent(PtkUIContent):
    """Content generated by a user control.

    Adds ability to search for the position of graphics.
    """

    @cached_property
    def graphic_positions(self) -> dict[str, Point]:
        """Scan content lines for graphic markers and return their positions.

        Returns:
            Dictionary mapping graphic keys to their (x, y) positions in content coordinates.
        """
        positions: dict[str, Point] = {}
        get_line = self.get_line
        for y in range(self.line_count):
            line = get_line(y)
            x = 0
            for style, text, *_ in line:
                for part in style.split():
                    if part.startswith("[Graphic_"):
                        key = part[9:-1]  # Extract key from [Graphic_xxx]
                        positions[key] = Point(x, y)
                    if part in _ZERO_WIDTH_FRAGMENTS:
                        break
                else:
                    x += get_cwidth(text)
        return positions


class DummyControl(UIControl):
    """A dummy control object that doesn't paint any content."""

    def create_content(self, width: int, height: int) -> UIContent:
        """Return one blank line only."""

        def get_line(i: int) -> StyleAndTextTuples:
            return []

        return UIContent(get_line=get_line, line_count=1)


class FocusableDummyControl(DummyControl):
    """A dummy control object that doesn't paint any content."""

    def is_focusable(self) -> bool:
        """Make this control focusable."""
        return True
