from collections.abc import Generator, Iterable
from typing import Union

from apptk.buffer import Buffer

from .containers import (
    AnyContainer,
    Container,
    Window,
)
from .controls import BufferControl, SearchBufferControl, UIControl

FocusableElement = Union[str, Buffer, UIControl, AnyContainer]

__all__ = [
    "InvalidLayoutError",
    "Layout",
    "walk",
]

def walk(container: Container, skip_hidden: bool = False) -> Iterable[Container]: ...

class Layout:
    container: AnyContainer
    _stack: list[Window]
    search_links: dict[SearchBufferControl, BufferControl]
    _child_to_parent: dict[Container, Container]
    visible_windows: list[Window]
    def __init__(
        self,
        container: AnyContainer,
        focused_element: FocusableElement | None = None,
    ) -> None: ...
    def find_all_windows(self) -> Generator[Window]: ...
    def find_all_controls(self) -> Iterable[UIControl]: ...
    def focus(self, value: FocusableElement) -> None: ...
    def has_focus(self, value: FocusableElement) -> bool: ...
    @property
    def current_control(self) -> UIControl: ...
    @current_control.setter
    def current_control(self, control: UIControl) -> None: ...
    @property
    def current_window(self) -> Window: ...
    @current_window.setter
    def current_window(self, value: Window) -> None: ...
    @property
    def is_searching(self) -> bool: ...
    @property
    def search_target_buffer_control(self) -> BufferControl | None: ...
    def get_focusable_windows(self) -> Iterable[Window]: ...
    def get_visible_focusable_windows(self) -> list[Window]: ...
    @property
    def current_buffer(self) -> Buffer | None: ...
    def get_buffer_by_name(self, buffer_name: str) -> Buffer | None: ...
    @property
    def buffer_has_focus(self) -> bool: ...
    @property
    def previous_control(self) -> UIControl: ...
    def focus_last(self) -> None: ...
    def focus_next(self) -> None: ...
    def focus_previous(self) -> None: ...
    def walk(self) -> Iterable[Container]: ...
    def walk_through_modal_area(self) -> Iterable[Container]: ...
    def update_parents_relations(self) -> None: ...
    def reset(self) -> None: ...
    def get_parent(self, container: Container) -> Container | None: ...
    def __repr__(self) -> str: ...

class InvalidLayoutError(Exception): ...
