Set Cols 160
Set Rows 40

Hide
Source common.setup.tape

# Show the TOML configuration file in the notebook editor
Type@0 "euporie notebook"
Enter
Sleep 2s
Alt+:
Type@0 'set-always-show-tab-bar True'
Enter
Sleep 0.1
Alt+:
Type@0 'set-syntax-theme monokai'
Enter
Sleep 0.1
Alt+:
Type@0 'set-color-scheme dark'
Enter
Sleep 0.1
Alt+:
Type@0 'set-max-notebook-width 120'
Enter
Sleep 0.1

Alt+:
Type@0 'open-config-file'
Enter
Sleep 1
Alt+S
Down
End
Sleep 1

Screenshot gallery.v3.toml-config.png
