Set Cols 80
Set Rows 20

Hide
Source common.setup.tape

# Launch with a new notebook
Type@0 "euporie notebook"
Enter
Sleep 2s
Ctrl+N
Sleep 2
# Enter code into a cell
Type@0 m
Enter
Type@0 '## Default'
Sleep 0.1
Ctrl+E
Sleep 0.1
Type@0 ':set-color-scheme-default'
Enter
Show
Sleep 2

Alt+S
Sleep 0.5
Down
Sleep 0.5
Down
Sleep 0.5
Right
Sleep 1
Hide
Enter

Enter
Ctrl+A
Type@0 '## Black'
Sleep 0.1
Ctrl+E
Show
Sleep 2

Hide
Type@0 ':set-color-scheme-dark'
Enter
Enter
Ctrl+A
Type@0 '## Dark'
Sleep 0.1
Ctrl+E
Show
Sleep 2

Hide
Type@0 ':set-color-scheme-light'
Enter
Enter
Ctrl+A
Type@0 '## Light'
Sleep 0.1
Ctrl+E
Show
Sleep 2

Hide
Type@0 ':set-color-scheme-white'
Enter
Enter
Ctrl+A
Type@0 '## White'
Sleep 0.1
Ctrl+E
Show
Sleep 2

Hide
Type@0 ':set-color-scheme-default'
Enter
Type@0 ':set-color-scheme-inverse'
Enter
Enter
Ctrl+A
Type@0 '## Inverse'
Sleep 0.1
Ctrl+E
Show
Sleep 2

Hide
Type@0 ':set-color-scheme-custom'
Enter
Enter
Ctrl+A
Type@0 '## Custom'
Sleep 0.1
Ctrl+E
Type@0 ':set-custom-foreground-color #839496'
Enter
Sleep 0.1
Type@0 ':set-custom-background-color #073642'
Enter
Sleep 0.1
Type@0 ':set-accent-color #225f65'
Enter
Sleep 0.1
Show
Sleep 2

Hide
Type@0 ':set-custom-foreground-color #e3e1e4'
Enter
Sleep 0.1
Type@0 ':set-custom-background-color #2d2a2e'
Enter
Sleep 0.1
Type@0 ':set-accent-color #fa5e84'
Enter
Sleep 0.1
Show
Sleep 2

Hide
Type@0 ':set-custom-foreground-color ##ffffff'
Enter
Sleep 0.1
Type@0 ':set-custom-background-color #54002b'
Enter
Sleep 0.1
Type@0 ':set-accent-color #8E4585'
Enter
Sleep 0.1
Show
Sleep 2

Hide
Type@0 ':set-custom-foreground-color #000000'
Enter
Sleep 0.1
Type@0 ':set-custom-background-color #cecb00'
Enter
Sleep 0.1
Type@0 ':set-accent-color #cc0403'
Enter
Enter
Ctrl+A
Type@0 '# Custom'
Sleep 0.1
Ctrl+E
Sleep 0.1
Show
Sleep 2

Ctrl+Q
Sleep 1
Tab
Sleep 1
Enter
Sleep 1


