import logging
from abc import abstractmethod
from collections.abc import Callable
from typing import TYPE_CHECKING, ContextManager

from apptk.key_binding import KeyPress

if TYPE_CHECKING:
    from collections.abc import Callable
    from contextlib import AbstractContextManager

log = logging.getLogger(__name__)

__all__ = [
    "DummyInput",
    "Input",
    "PipeInput",
]

class Input:
    @abstractmethod
    def fileno(self) -> int: ...
    @abstractmethod
    def typeahead_hash(self) -> str: ...
    @abstractmethod
    def read_keys(self) -> list[KeyPress]: ...
    def flush_keys(self) -> list[KeyPress]: ...
    def flush(self) -> None: ...
    @property
    @abstractmethod
    def closed(self) -> bool: ...
    @abstractmethod
    def raw_mode(self) -> ContextManager[None]: ...
    @abstractmethod
    def cooked_mode(self) -> ContextManager[None]: ...
    @abstractmethod
    def attach(
        self, input_ready_callback: Callable[[], None]
    ) -> ContextManager[None]: ...
    @abstractmethod
    def detach(self) -> ContextManager[None]: ...
    def close(self) -> None: ...

class PipeInput(Input):
    @abstractmethod
    def send_bytes(self, data: bytes) -> None: ...
    @abstractmethod
    def send_text(self, data: str) -> None: ...

class DummyInput(Input):
    def fileno(self) -> int: ...
    def typeahead_hash(self) -> str: ...
    def read_keys(self) -> list[KeyPress]: ...
    @property
    def closed(self) -> bool: ...
    def raw_mode(self) -> ContextManager[None]: ...
    def cooked_mode(self) -> ContextManager[None]: ...
    def attach(
        self, input_ready_callback: Callable[[], None]
    ) -> ContextManager[None]: ...
    def detach(self) -> ContextManager[None]: ...

class IgnoredInput(DummyInput):
    def attach(
        self,
        input_ready_callback: Callable[[], None],
    ) -> AbstractContextManager[None]: ...
