from contextlib import AbstractContextManager
from typing import ContextManager

from .base import PipeInput
from .vt100 import Vt100Input

__all__ = [
    "PosixPipeInput",
]

class _Pipe:
    _read_closed = False
    _write_closed = False
    def __init__(self) -> None: ...
    def close_read(self) -> None: ...
    def close_write(self) -> None: ...
    def close(self) -> None: ...

class PosixPipeInput(Vt100Input, PipeInput):
    _id = 0
    pipe: _Pipe
    def __init__(self, _pipe: _Pipe, _text: str = "") -> None: ...
    @classmethod
    def create(cls, text: str = "") -> AbstractContextManager[PosixPipeInput]: ...
    def send_bytes(self, data: bytes) -> None: ...
    def send_text(self, data: str) -> None: ...
    def raw_mode(self) -> ContextManager[None]: ...
    def cooked_mode(self) -> ContextManager[None]: ...
    def close(self) -> None: ...
    def typeahead_hash(self) -> str: ...
