from collections.abc import Callable
from contextlib import AbstractContextManager
from ctypes.wintypes import HANDLE
from typing import ContextManager

from apptk.eventloop.win32 import create_win32_event

from ..key_binding import KeyPress
from .base import PipeInput
from .vt100_parser import Vt100Parser
from .win32 import _Win32InputBase

__all__ = [
    "Win32PipeInput",
]

class Win32PipeInput(_Win32InputBase, PipeInput):
    _id = 0
    _event = create_win32_event()
    _closed = False
    _buffer: list[KeyPress]
    vt100_parser: Vt100Parser
    def __init__(self, _event: HANDLE) -> None: ...
    @classmethod
    def create(cls) -> AbstractContextManager[Win32PipeInput]: ...
    @property
    def closed(self) -> bool: ...
    def fileno(self) -> int: ...
    @property
    def handle(self) -> HANDLE: ...
    def attach(
        self, input_ready_callback: Callable[[], None]
    ) -> ContextManager[None]: ...
    def detach(self) -> ContextManager[None]: ...
    def read_keys(self) -> list[KeyPress]: ...
    def flush_keys(self) -> list[KeyPress]: ...
    def send_bytes(self, data: bytes) -> None: ...
    def send_text(self, text: str) -> None: ...
    def raw_mode(self) -> ContextManager[None]: ...
    def cooked_mode(self) -> ContextManager[None]: ...
    def close(self) -> None: ...
    def typeahead_hash(self) -> str: ...
