"""This package defines the euporie application and its components."""

__app_name__ = "euporie"
__version__ = "1.4.2"
__logo__ = "⚈"
__strapline__ = "A TUI editor for Jupyter notebooks"
__author__ = "Josiah Outram Halstead"
__email__ = "josiah@halstead.email"
__copyright__ = f"© 2022, {__author__}"
__license__ = "MIT"
