import re
import weakref
from collections.abc import Callable, Iterable
from re import Pattern
from typing import NoReturn, cast

from .clipboard import ClipboardData
from .selection import PasteMode, SelectionState

_FIND_WORD_RE = re.compile(r"([a-zA-Z0-9_]+|[^a-zA-Z0-9_\s]+)")
_FIND_CURRENT_WORD_RE = re.compile(r"^([a-zA-Z0-9_]+|[^a-zA-Z0-9_\s]+)")
_FIND_CURRENT_WORD_INCLUDE_TRAILING_WHITESPACE_RE = re.compile(
    r"^(([a-zA-Z0-9_]+|[^a-zA-Z0-9_\s]+)\s*)"
)
_FIND_BIG_WORD_RE = re.compile(r"([^\s]+)")
_FIND_CURRENT_BIG_WORD_RE = re.compile(r"^([^\s]+)")
_FIND_CURRENT_BIG_WORD_INCLUDE_TRAILING_WHITESPACE_RE = re.compile(r"^([^\s]+\s*)")
_text_to_document_cache: dict[str, _DocumentCache] = cast(
    dict[str, "_DocumentCache"],
    weakref.WeakValueDictionary(),  # Maps document.text to DocumentCache instance.
)

__all__ = [
    "Document",
]

class _ImmutableLineList(list[str]):
    __setitem__ = _error
    append = _error
    clear = _error
    extend = _error
    insert = _error
    pop = _error
    remove = _error
    reverse = _error
    sort = _error
    def _error(self, *a: object, **kw: object) -> NoReturn: ...

class _DocumentCache:
    lines: _ImmutableLineList | None
    line_indexes: list[int] | None
    def __init__(self) -> None: ...

class Document:
    __slots__ = ("_cache", "_cursor_position", "_selection", "_text")
    _text: str
    _cursor_position: int | None
    _selection: SelectionState | None
    _cache = _text_to_document_cache[self.text]
    def __init__(
        self,
        text: str = "",
        cursor_position: int | None = None,
        selection: SelectionState | None = None,
    ) -> None: ...
    def __repr__(self) -> str: ...
    def __eq__(self, other: object) -> bool: ...
    @property
    def text(self) -> str: ...
    @property
    def cursor_position(self) -> int: ...
    @property
    def selection(self) -> SelectionState | None: ...
    @property
    def current_char(self) -> str: ...
    @property
    def char_before_cursor(self) -> str: ...
    @property
    def text_before_cursor(self) -> str: ...
    @property
    def text_after_cursor(self) -> str: ...
    @property
    def current_line_before_cursor(self) -> str: ...
    @property
    def current_line_after_cursor(self) -> str: ...
    @property
    def lines(self) -> list[str]: ...
    @property
    def _line_start_indexes(self) -> list[int]: ...
    @property
    def lines_from_current(self) -> list[str]: ...
    @property
    def line_count(self) -> int: ...
    @property
    def current_line(self) -> str: ...
    @property
    def leading_whitespace_in_current_line(self) -> str: ...
    def _get_char_relative_to_cursor(self, offset: int = 0) -> str: ...
    @property
    def on_first_line(self) -> bool: ...
    @property
    def on_last_line(self) -> bool: ...
    @property
    def cursor_position_row(self) -> int: ...
    @property
    def cursor_position_col(self) -> int: ...
    def _find_line_start_index(self, index: int) -> tuple[int, int]: ...
    def translate_index_to_position(self, index: int) -> tuple[int, int]: ...
    def translate_row_col_to_index(self, row: int, col: int) -> int: ...
    @property
    def is_cursor_at_the_end(self) -> bool: ...
    @property
    def is_cursor_at_the_end_of_line(self) -> bool: ...
    def has_match_at_current_position(self, sub: str) -> bool: ...
    def find(
        self,
        sub: str,
        in_current_line: bool = False,
        include_current_position: bool = False,
        ignore_case: bool = False,
        count: int = 1,
    ) -> int | None: ...
    def find_all(self, sub: str, ignore_case: bool = False) -> list[int]: ...
    def find_backwards(
        self,
        sub: str,
        in_current_line: bool = False,
        ignore_case: bool = False,
        count: int = 1,
    ) -> int | None: ...
    def get_word_before_cursor(
        self,
        WORD: bool = False,
        pattern: Pattern[str] | None = None,
    ) -> str: ...
    def _is_word_before_cursor_complete(
        self,
        WORD: bool = False,
        pattern: Pattern[str] | None = None,
    ) -> bool: ...
    def find_start_of_previous_word(
        self,
        count: int = 1,
        WORD: bool = False,
        pattern: Pattern[str] | None = None,
    ) -> int | None: ...
    def find_boundaries_of_current_word(
        self,
        WORD: bool = False,
        include_leading_whitespace: bool = False,
        include_trailing_whitespace: bool = False,
    ) -> tuple[int, int]: ...
    def get_word_under_cursor(self, WORD: bool = False) -> str: ...
    def find_next_word_beginning(
        self, count: int = 1, WORD: bool = False
    ) -> int | None: ...
    def find_next_word_ending(
        self,
        include_current_position: bool = False,
        count: int = 1,
        WORD: bool = False,
    ) -> int | None: ...
    def find_previous_word_beginning(
        self,
        count: int = 1,
        WORD: bool = False,
    ) -> int | None: ...
    def find_previous_word_ending(
        self,
        count: int = 1,
        WORD: bool = False,
    ) -> int | None: ...
    def find_next_matching_line(
        self,
        match_func: Callable[[str], bool],
        count: int = 1,
    ) -> int | None: ...
    def find_previous_matching_line(
        self,
        match_func: Callable[[str], bool],
        count: int = 1,
    ) -> int | None: ...
    def get_cursor_left_position(self, count: int = 1) -> int: ...
    def get_cursor_right_position(self, count: int = 1) -> int: ...
    def get_cursor_up_position(
        self,
        count: int = 1,
        preferred_column: int | None = None,
    ) -> int: ...
    def get_cursor_down_position(
        self,
        count: int = 1,
        preferred_column: int | None = None,
    ) -> int: ...
    def find_enclosing_bracket_right(
        self,
        left_ch: str,
        right_ch: str,
        end_pos: int | None = None,
    ) -> int | None: ...
    def find_enclosing_bracket_left(
        self,
        left_ch: str,
        right_ch: str,
        start_pos: int | None = None,
    ) -> int | None: ...
    def find_matching_bracket_position(
        self,
        start_pos: int | None = None,
        end_pos: int | None = None,
    ) -> int: ...
    def get_start_of_document_position(self) -> int: ...
    def get_end_of_document_position(self) -> int: ...
    def get_start_of_line_position(self, after_whitespace: bool = False) -> int: ...
    def get_end_of_line_position(self) -> int: ...
    def last_non_blank_of_current_line_position(self) -> int: ...
    def get_column_cursor_position(self, column: int) -> int: ...
    def selection_range(self) -> tuple[int, int]: ...
    def selection_ranges(self) -> Iterable[tuple[int, int]]: ...
    def selection_range_at_line(self, row: int) -> tuple[int, int] | None: ...
    def cut_selection(self) -> tuple[Document, ClipboardData]: ...
    def paste_clipboard_data(
        self,
        data: ClipboardData,
        paste_mode: PasteMode = PasteMode.EMACS,
        count: int = 1,
    ) -> Document: ...
    def empty_line_count_at_the_end(self) -> int: ...
    def start_of_paragraph(self, count: int = 1, before: bool = False) -> int: ...
    def end_of_paragraph(self, count: int = 1, after: bool = False) -> int: ...
    def insert_after(self, text: str) -> Document: ...
    def insert_before(self, text: str) -> Document: ...
