import os
import threading
from abc import abstractmethod
from collections.abc import AsyncGenerator, Iterable, Sequence
from typing import Union

_StrOrBytesPath = Union[str, bytes, "os.PathLike[str]", "os.PathLike[bytes]"]

__all__ = [
    "DummyHistory",
    "FileHistory",
    "History",
    "InMemoryHistory",
    "ThreadedHistory",
]

class History:
    _loaded = False
    _loaded_strings: list[str]
    def __init__(self) -> None: ...
    async def load(self) -> AsyncGenerator[str]: ...
    def get_strings(self) -> list[str]: ...
    def append_string(self, string: str) -> None: ...
    @abstractmethod
    def load_history_strings(self) -> Iterable[str]: ...
    @abstractmethod
    def store_string(self, string: str) -> None: ...

class ThreadedHistory(History):
    history: History
    _load_thread: threading.Thread | None
    _lock: threading.Lock
    _string_load_events: list[threading.Event]
    _loaded_strings = []
    _loaded = True
    def __init__(self, history: History) -> None: ...
    async def load(self) -> AsyncGenerator[str]: ...
    def _in_load_thread(self) -> None: ...
    def append_string(self, string: str) -> None: ...
    def load_history_strings(self) -> Iterable[str]: ...
    def store_string(self, string: str) -> None: ...
    def __repr__(self) -> str: ...

class InMemoryHistory(History):
    _storage = []
    def __init__(self, history_strings: Sequence[str] | None = None) -> None: ...
    def load_history_strings(self) -> Iterable[str]: ...
    def store_string(self, string: str) -> None: ...

class DummyHistory(History):
    def load_history_strings(self) -> Iterable[str]: ...
    def store_string(self, string: str) -> None: ...
    def append_string(self, string: str) -> None: ...

class FileHistory(History):
    filename: _StrOrBytesPath
    def __init__(self, filename: _StrOrBytesPath) -> None: ...
    def load_history_strings(self) -> Iterable[str]: ...
    def store_string(self, string: str) -> None: ...
