import asyncio
import queue
import threading
from contextlib import AbstractContextManager
from typing import TextIO

from .application import get_app_session
from .output import Output

__all__ = [
    "StdoutProxy",
    "patch_stdout",
]

def patch_stdout(raw: bool = False) -> AbstractContextManager[None]: ...

class _Done: ...

class StdoutProxy:
    sleep_between_writes: float
    raw: bool
    _lock: threading.RLock
    _buffer: list[str]
    app_session = get_app_session()
    _output: Output
    _flush_queue: queue.Queue[str | _Done]
    _flush_thread = self._start_write_thread()
    closed = False
    def __init__(
        self, sleep_between_writes: float = 0.2, raw: bool = False
    ) -> None: ...
    def __enter__(self) -> StdoutProxy: ...
    def __exit__(self, *args: object) -> None: ...
    def close(self) -> None: ...
    def _start_write_thread(self) -> threading.Thread: ...
    def _write_thread(self) -> None: ...
    def _get_app_loop(self) -> asyncio.AbstractEventLoop | None: ...
    def _write_and_flush(
        self,
        loop: asyncio.AbstractEventLoop | None,
        text: str,
    ) -> None: ...
    def _write(self, data: str) -> None: ...
    def _flush(self) -> None: ...
    def write(self, data: str) -> int: ...
    def flush(self) -> None: ...
    @property
    def original_stdout(self) -> TextIO | None: ...
    def fileno(self) -> int: ...
    def isatty(self) -> bool: ...
    @property
    def encoding(self) -> str: ...
    @property
    def errors(self) -> str: ...
