import sys
from collections import deque
from collections.abc import Callable, Generator
from typing import ContextManager, Generic, TypeVar, Union

SPHINX_AUTODOC_RUNNING = "sphinx.ext.autodoc" in sys.modules
_Sender = TypeVar("_Sender", covariant=True)

class _CharSizesCache(dict[str, int]):
    LONG_STRING_MIN_LEN = 64  # Minimum string length for considering it long.
    MAX_LONG_STRINGS = 16  # Maximum number of long strings to remember.
    _long_strings: deque[str]
    def __init__(self) -> None: ...
    def __missing__(self, string: str) -> int: ...

_CHAR_SIZES_CACHE = _CharSizesCache()
_T = TypeVar("_T")
AnyFloat = Union[Callable[[], float], float]

__all__ = [
    "AnyFloat",
    "DummyContext",
    "Event",
    "get_bell_environment_variable",
    "get_cwidth",
    "get_term_environment_variable",
    "in_main_thread",
    "is_conemu_ansi",
    "is_dumb_terminal",
    "is_windows",
    "suspend_to_background_supported",
    "take_using_weights",
    "to_float",
    "to_int",
    "to_str",
]

def get_cwidth(string: str) -> int: ...
def suspend_to_background_supported() -> bool: ...
def is_windows() -> bool: ...
def is_windows_vt100_supported() -> bool: ...
def is_conemu_ansi() -> bool: ...
def in_main_thread() -> bool: ...
def get_bell_environment_variable() -> bool: ...
def get_term_environment_variable() -> str: ...
def take_using_weights(items: list[_T], weights: list[int]) -> Generator[_T]: ...
def to_str(value: Callable[[], str] | str) -> str: ...
def to_int(value: Callable[[], int] | int) -> int: ...
def to_float(value: AnyFloat) -> float: ...
def is_dumb_terminal(term: str | None = None) -> bool: ...

class Event(Generic[_Sender]):
    sender: _Sender
    _handlers: list[Callable[[_Sender], None]]
    def __init__(
        self,
        sender: _Sender,
        handler: Callable[[_Sender], None] | None = None,
    ) -> None: ...
    def fire(self) -> None: ...
    def add_handler(self, handler: Callable[[_Sender], None]) -> None: ...
    def remove_handler(self, handler: Callable[[_Sender], None]) -> None: ...
    def __call__(self) -> None: ...
    def __iadd__(self, handler: Callable[[_Sender], None]) -> Event[_Sender]: ...
    def __isub__(self, handler: Callable[[_Sender], None]) -> Event[_Sender]: ...

class DummyContext(ContextManager[None]):
    def __enter__(self) -> None: ...
    def __exit__(self, *a: object) -> None: ...
