from abc import abstractmethod
from collections.abc import Callable

from apptk.selection import SelectionType

__all__ = [
    "Clipboard",
    "ClipboardData",
    "DummyClipboard",
    "DynamicClipboard",
]

class ClipboardData:
    text: str
    type: SelectionType
    def __init__(
        self,
        text: str = "",
        type: SelectionType = SelectionType.CHARACTERS,
    ) -> None: ...

class Clipboard:
    @abstractmethod
    def set_data(self, data: ClipboardData) -> None: ...
    def set_text(self, text: str) -> None: ...
    def rotate(self) -> None: ...
    @abstractmethod
    def get_data(self) -> ClipboardData: ...

class DummyClipboard(Clipboard):
    def set_data(self, data: ClipboardData) -> None: ...
    def set_text(self, text: str) -> None: ...
    def rotate(self) -> None: ...
    def get_data(self) -> ClipboardData: ...

class DynamicClipboard(Clipboard):
    get_clipboard: Callable[[], Clipboard | None]
    def __init__(self, get_clipboard: Callable[[], Clipboard | None]) -> None: ...
    def _clipboard(self) -> Clipboard: ...
    def set_data(self, data: ClipboardData) -> None: ...
    def set_text(self, text: str) -> None: ...
    def rotate(self) -> None: ...
    def get_data(self) -> ClipboardData: ...
